### ISSUE TITLE
when recent merge happened it updated symfony with recent version changing things and creating conflicts

### ISSUE THREAD

**Issue by CaleumSeanFoxNorbury** [CaleumSeanFoxNorbury/Final-Year-Project#14]
Main Error:

```
Script cache:clear returned with error code 255
!!  
!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineCacheBundle" from namespace "Doctrine\Bundle\DoctrineCacheBundle".
!!  Did you forget a "use" statement for another namespace? in C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\src\Kernel.php:23   
!!  Stack trace:
!!  #0 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\http-kernel\Kernel.php(429): App\Kernel->registerBundles()   
!!  #1 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\http-kernel\Kernel.php(130): Symfony\Component\HttpKernel\Kernel->initializeBundles()
!!  #2 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\framework-bundle\Console\Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\console\Application.php(149):  in C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\src\Kernel.php on line 23
!!  PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "DoctrineCacheBundle" from namespace "Doctrine\Bundle\DoctrineCacheBundle".
!!  Did you forget a "use" statement for another namespace? in C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\src\Kernel.php:23   
!!  Stack trace:
!!  #0 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\http-kernel\Kernel.php(429): App\Kernel->registerBundles()   
!!  #1 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symnel->initializeBundles()
!!  #2 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\framework-bundle\Console\Application.php(159): Symfony\Component\HttpKernel\Kernel->boot()
!!  #3 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\framework-bundle\Console\Application.php(65): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
!!  #4 C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\vendor\symfony\console\Application.php(149):  in C:\xampp\htdocs\testRun\Final-Year-Project-dev-1\src\Kernel.php on line 23
!!
```

solved:

Required updated bundle as the previous bundle was removed/outdated.

```
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
```

**Comment by CaleumSeanFoxNorbury** [comment]
Solved! Keep open for future referencing
